name: cwm
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2024.7.2
  - ld_impl_linux-64=2.40
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - ncurses=6.4
  - openssl=3.0.15
  - pip=24.2
  - python=3.10.14
  - readline=8.2
  - setuptools=75.1.0
  - sqlite=3.45.3
  - tk=8.6.14
  - wheel=0.44.0
  - xz=5.4.6
  - zlib=1.2.13
  - pip:
      - aiohappyeyeballs==2.4.2
      - aiohttp==3.10.6
      - aiosignal==1.3.1
      - annotated-types==0.7.0
      - anyio==4.6.0
      - async-timeout==4.0.3
      - attrs==24.2.0
      - beautifulsoup4==4.12.3
      - certifi==2024.8.30
      - charset-normalizer==3.3.2
      - click==8.1.7
      - colorama==0.4.6
      - dataclasses-json==0.6.7
      - deprecated==1.2.14
      - dirtyjson==1.0.8
      - distro==1.9.0
      - dnspython==2.6.1
      - email-validator==2.2.0
      - exceptiongroup==1.2.2
      - fastapi==0.111.0
      - fastapi-cli==0.0.5
      - frozenlist==1.4.1
      - fsspec==2024.9.0
      - greenlet==3.1.1
      - h11==0.14.0
      - httpcore==1.0.5
      - httptools==0.6.1
      - httpx==0.27.2
      - idna==3.10
      - jinja2==3.1.4
      - joblib==1.4.2
      - jsonpatch==1.33
      - jsonpointer==3.0.0
      - langchain==0.2.16
      - langchain-core==0.2.41
      - langchain-openai==0.1.20
      - langchain-text-splitters==0.2.4
      - langsmith==0.1.129
      - llama-cloud==0.0.6
      - llama-index==0.10.53
      - llama-index-agent-openai==0.2.9
      - llama-index-cli==0.1.13
      - llama-index-core==0.10.53.post1
      - llama-index-embeddings-openai==0.1.11
      - llama-index-indices-managed-llama-cloud==0.2.4
      - llama-index-legacy==0.9.48.post3
      - llama-index-llms-openai==0.1.26
      - llama-index-multi-modal-llms-openai==0.1.9
      - llama-index-program-openai==0.1.6
      - llama-index-question-gen-openai==0.1.3
      - llama-index-readers-file==0.1.33
      - llama-index-readers-llama-parse==0.1.6
      - llama-parse==0.4.9
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - marshmallow==3.22.0
      - mdurl==0.1.2
      - multidict==6.1.0
      - mypy-extensions==1.0.0
      - nest-asyncio==1.6.0
      - networkx==3.3
      - nltk==3.9.1
      - numpy==1.26.4
      - openai==1.35.12
      - orjson==3.10.7
      - packaging==24.1
      - pandas==2.2.0
      - pillow==10.4.0
      - prettytable==3.7.0
      - pydantic==2.9.2
      - pydantic-core==2.23.4
      - pygments==2.18.0
      - pymysql==1.0.3
      - pypdf==4.3.1
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.0.0
      - python-multipart==0.0.10
      - pytz==2024.2
      - pyyaml==6.0.2
      - regex==2024.9.11
      - requests==2.32.3
      - rich==13.8.1
      - shellingham==1.5.4
      - six==1.16.0
      - sniffio==1.3.1
      - soupsieve==2.6
      - sqlalchemy==1.4.49
      - starlette==0.37.2
      - striprtf==0.0.26
      - tenacity==8.5.0
      - tiktoken==0.7.0
      - tqdm==4.66.5
      - typer==0.12.5
      - typing-extensions==4.12.2
      - typing-inspect==0.9.0
      - tzdata==2024.2
      - ujson==5.10.0
      - urllib3==2.2.3
      - uvicorn==0.30.1
      - uvloop==0.20.0
      - watchfiles==0.24.0
      - wcwidth==0.2.13
      - websockets==13.1
      - wrapt==1.16.0
      - yarl==1.13.0
