import json

en = [
    "What orders has the PolyU placed?",
    "Have all of John's orders been completed?",
    "What is the production progress of the Dress ordered by Emily? Please represent it in percentage.",
    "What products are included in James's order?",
    "When was Sophia's order created?",
    "What products are included in PolyU's January orders?",
    "How many orders are there in total under PolyU?",
    "What materials were used in Olivia's order?",
    "What is the progress of sewing tasks for William?",
    "For Michael's SweaterAndShorts order, which other products have not been manufactured yet? Please list the types and quantities of unfinished products.",

    "What are the cutting tasks completed on April 30, 2024?",
    "What are the sewing tasks completed on May 31, 2024?",
    "What are the raw materials with non zero inventory in all of our warehouses, organized in the form of 'Type: Remaining Quantity'?",
    "What is the material with the highest remaining inventory?",
    "What is the material with the lowest remaining inventory?",
    "What are the cutting tasks that will only start after May 1, 2024?",
    "What are the sewing tasks after June 1, 2024?",
    "Which cutting tasks use Cotton Fabric?",
    "Which sewing tasks use Silk?",
    "Which products have zero remaining inventory?",
    "List the work tasks of Advanced Sewers from April to May 2024.",
    "What sewing groups and cutting groups do we have now?",
    "Which warehouse has more Cotton Fabric between the main and auxiliary warehouses?",

    "What are the sewing tasks assigned by Elite Sewers before April 30, 2024?",
    "What are the sewing tasks completed by Master Sewers in May 2024?",
    "What raw materials are used by Skilled Sewers?",
    "I am Advanced Sewers. What are the tasks I have not yet completed?",
    "Have all the sewing tasks for the orders placed by the Hong Kong Polytechnic University in January been completed?",
    "Which sewing task has the lowest completion percentage among the unfinished sewing tasks before June 2024? List the names of team members.",
    "How many sewing tasks did Skilled Sewers complete before June 2024, and what types of products were produced for these sewing tasks?",
    "What are the sewing tasks of Premier Sewers?",
    "What are the sewing tasks for Dress's product type?",
    "What are the current cutting tasks assigned to Precision Cutters?",
    "Which cutting tasks have been completed by Master Cutters?",
    "Which materials were used in the cutting tasks by Expert Cutters?",
    "What are the cutting tasks for customers who are PolyU?",
    "What is the task with the highest planned cutting quantity among all unfinished cutting tasks before June 2024?",
    "How is the progress of cutting tasks by Advanced?",
    "Which cutting tasks use Leather?",
    "Which cutting tasks are for products categorized as T-shirt?",

    "I am from Hong Kong Polytechnic University, and today is July 2, 2024. Please help me create an order for 50 Red, size M T-shirts, and 30 Blue, size XL Sweaters.",
    "For orders submitted by PolyU in January 2024, set all sewing tasks for producing Yellow, S size type T-shirts to start status. ",
    "Send 1000 Leathers to the Main Warehouse for storage.",
    "100 Cotton Fabrics will be shipped from the main warehouse.",
    "Product inventory (Auxiliary), with 100 pieces of product p15 stored.",
    "For the cutting task with the number sw34, allocate cutting materials from Cotton Fabric in Main Warehouse, 30 meters.",
    "Create a cutting task for the order from the Hong Kong Polytechnic University on May 10th, with a task period from June 30th to July 12th, and the cutting team responsible is Expert Cutters. Other fields are temporarily left blank. Return the cropping task number.",
    "I am Advanced Sewers. Please transfer all my cropping tasks for May 2024 to Premier Sewers.",
    "I have completed all the workload for the sewing task with number sw34. Please update the completed quantity.",
    "For cropping task number ct33, the end time needs to be delayed until July 31, 2024"
]

ch = [
    "PolyU的订单有哪些？",
    "John 的订单全部生产完成了么？",
    "Emily订购的Dress订单生产进度如何？用百分比来表示。",
    "James 的订单包含哪些产品？",
    "Sophia的订单创建时间是什么时候？",
    "顾客理大1月的订单包含哪些产品？",
    "顾客PolyU 下的订单总数是多少？",
    "Olivia的订单中使用了哪些原料？",
    "William 的缝纫任务进度如何？",
    "对于Michael下的SweaterAndShorts的订单，还有哪些产品没有制造完成，列出未完成产品的类型和数量？",

    "2024年4月30日完成的裁剪任务有哪些？",
    "2024年5月31日完成的缝纫任务有哪些？",
    "在我们的所有仓库中，库存不为0的原材料有哪些，整理成{类型：剩余数量}的形式。",
    "剩余库存最多的原料是什么？",
    "剩余库存最少的原料是什么？",
    "2024年5月1日后才开始的裁剪任务有哪些？",
    "2024年6月1日后的缝纫任务有哪些？",
    "使用 Cotton Fabric 的裁剪任务有哪些？",
    "使用 Silk 的缝纫任务有哪些？",
    "剩余库存为零的材料有哪些，列出材料名字？",
    "列出Advanced Sewers在2024年4月到5月的工作任务。",
    "我们现在有哪些缝纫组，哪些裁剪组？",
    "主仓库和辅助仓库中，哪个仓库的Cotton Fabric更多？",

    "Elite Sewers 在2024年4月30日前分配的缝纫任务有哪些？",
    "Master Sewers 在2024年5月完成的缝纫任务有哪些？",
    "Skilled Sewers使用了哪些原料？",
    "我是Advanced Sewers，我尚未完成的任务有哪些？",
    "香港理工大学 1月份下的订单的缝纫任务全部完成了么？",
    "2024年6月前未完成的缝纫任务中，完成度百分比最低的缝纫任务是哪个？列出工作组人员名称。",
    "Skilled Sewers 在2024年6月前完成了多少个缝纫任务，这些缝纫任务都做了什么类型的产品？",
    "Premier Sewers的缝纫任务有哪些？",
    "产品类型是Dress的缝纫任务有哪些？",
    "Precision Cutters当前分配的裁剪任务有哪些？",
    "Master Cutters当前已完成的裁剪任务有哪些？",
    "Expert Cutters 的裁剪任务中使用了哪些原料？",
    "顾客是PolyU 的裁剪任务有哪些？",
    "在2024年6月前所有未完成的裁剪任务中，计划裁剪数量最多的任务是什么？",
    "Advanced 的裁剪任务进度如何？",
    "使用 Leather 的裁剪任务有哪些？",
    "订单产品是T恤的裁剪任务有哪些？",

    "我是香港理工大学，今天是2024年7月2日，请帮我创建一个订单，要50件Red, M size的T-shirt, 以及30件Blue, XL size 的Sweater。",
    "对于PolyU在2024年1月提交的订单，将所有生产Yellow, S size类型T-shirt的缝纫任务设置成开始状态。",
    "向仓库Main Warehouse，入库Leather 1000份。",
    "产品入库（Auxiliary，入库p15号产品100件。",
    "主仓库出库Cotton Fabric100份。",
    "对于编号为sw34的裁剪任务，分配裁剪物料，物料来源：Main Warehouse的Cotton Fabric，30米。",
    "为香港理工大学5月10日的订单创建裁剪一个任务，任务期为6月30日到7月12日，负责的裁剪团队为Expert Cutters。其他字段暂时留空。返回裁剪任务编号。",
    "我是Advanced Sewers，请将2024年5月，属于我的所有裁剪任务转给Premier Sewers。",
    "对于编号为sw34的缝纫任务，所有的工作量我都已完成，请更新已完成数量。",
    "对于编号为ct33的裁剪任务，结束时间需要延迟至2024年7月31日"
]

if __name__ == '__main__':
    for id in range(1, 50):
        data = {
            "ID": id + 1,
            "q_ch": ch[id],
            "q_en": en[id],
            "gt": ""
        }
        with open(f'../../questions/q0702/{id + 1}.json', 'w', encoding='utf-8') as file:
            json.dump(data, file, ensure_ascii=False, indent=4)
