version: "3"

services:
  mysql:
    image: mysql:5.7
    container_name: fashion-mysql
    environment:
      MYSQL_ROOT_PASSWORD: Fashion!@#
    ports:
      - "41970:3306"
    volumes:
      - ./charset_and_collation.cnf:/etc/mysql/conf.d/my_custom.cnf
      - ./mysql_data:/var/lib/mysql
      - ./create_fashion_database.sql:/docker-entrypoint-initdb.d/init-db.sql 
    restart: always
