services:
  mysql:
    image: mysql:5.7
    container_name: fashion-mysql
    environment:
      MYSQL_ROOT_PASSWORD: Fashion!@#
      MYSQL_CHARSET: utf8mb4
      MYSQL_COLLATION: utf8mb4_unicode_ci
    ports:
      - "41970:3306"
    volumes:
      -  ./mysql_data:/var/lib/mysql
      - ./create_fashion_database.sql:/docker-entrypoint-initdb.d/init-db.sql 
    restart: always
